name: conda-env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.2=py39h7cc1a96_1
  - ca-certificates=2020.10.14=0
  - certifi=2021.5.30=py39haa95532_0
  - intel-openmp=2021.3.0=haa95532_3372
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.2=py39hf11a4ad_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - numpy=1.20.3=py39ha4e8547_0
  - numpy-base=1.20.3=py39hc2deb75_0
  - openssl=1.1.1k=h8ffe710_1
  - pandas=1.3.1=py39h6214cd6_0
  - pip=21.2.4=py38haa95532_0
  - progressbar=2.5=py_0
  - python=3.9.6=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py39h2bbff1b_1
  - setuptools=52.0.0=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tzdata=2021a=h5d7bf9c_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_0
  - wincertstore=0.2=py39h2bbff1b_0
  - yaml=0.2.5=he774522_0
prefix: C:\Users\Leo\anaconda3\envs\conda-env
